<div class="card">
    <div class="card-body" >
        <div id="query_builder_wrapper" class="dataTables_wrapper dt-bootstrap4">
            <?php if(!empty($Reportsofdak)):?>
                <table  id="ReportFileTrap" class="table table-bordered table-striped">
                    <thead><tr>
                        <th>SNo.</th>
                        <th>Diary No.</th>
                        <th>Reg. No.</th>
                        <th>Document Description</th>
                        <th>Remark</th><th>Status</th>
                        <th>Filed By</th>
                        <th>Advocate</th>
                        <th>Generated By/Date-time</th>
                    </tr></thead><tbody>
                    <?php $sno = 1; foreach($Reportsofdak as $row):?>
                        <tr>
                            <th><?php echo $sno;?></th>
                            <td><?php echo substr($row->diary_no,0,-4).'/'.substr($row->diary_no,-4);?></td>
                            <td><?php echo $row->short_description.SUBSTR($row->active_fil_no,3).'/'.$row->active_reg_year;?></td>
                            <td><?php
                                echo $row->docnum.'/'.$row->docyear.' - ';
                                if($row->doccode==8) echo "I.A.- ";
                                echo $row->docdesc; if($row->other1 != '') echo ' - '.$row->other1;
                                ?></td>
                            <td><?php echo $row->remark; ?></td>
                            <td><?php if($row->doccode==8){ if($row->iastat=='P') echo "Pending"; else if($row->iastat=='D') echo "Disposed";}?></td>
                            <td><?php echo $row->filedby; ?></td><td><?php echo $row->advname; ?></td>
                            <td><?php echo $row->entryuser.'/'.date('d-m-Y h:i:s A',strtotime($row->ent_dt)); ?></td>
                            </tr>
                    <?php $sno++; endforeach; ?>
                    </tbody>
                </table>
            <?php else: { echo "Record Not Found"; } endif; ?>
            <!-- end of fileTrap -->
        </div>
        <script>
            $(function () {
                $("#ReportFileTrap").DataTable({
                    "responsive": true, "lengthChange": false, "autoWidth": false,
                    "buttons": ["copy", "csv", "excel",{extend: 'pdfHtml5',orientation: 'landscape',pageSize: 'LEGAL' },
                        { extend: 'colvis',text: 'Show/Hide'}],"bProcessing": true,"extend": 'colvis',"text": 'Show/Hide'
                }).buttons().container().appendTo('#query_builder_wrapper .col-md-6:eq(0)');

                });
        </script>
