<?php
if(!empty($row)){
    $output = '';
        $output .= '<center><b>Statistical Information As On ' . date('d-m-Y', strtotime($row['filing_date'])) . ' at ' . $row['updation_time'] . '</b></center><br/><br/>
<table width="100%" cellpadding="5" cellspacing="5" style="border: 1px solid #000000; border-collapse: collapse;">
    <tr style="border: 1px solid #000000; border-collapse: collapse;"><th colspan="4" style="border: 1px solid #000000; border-collapse: collapse;">Filing</th><th colspan="4" style="border: 1px solid #000000; border-collapse: collapse;"></th></tr>
    <tr style="border: 1px solid #000000; border-collapse: collapse;"><th style="border: 1px solid #000000; border-collapse: collapse;">Total</th><th style="border: 1px solid #000000; border-collapse: collapse;">Physical</th><th style="border: 1px solid #000000; border-collapse: collapse;">SC-efm Filing</th><th style="border: 1px solid #000000; border-collapse: collapse;">Re-Filed</th><th style="border: 1px solid #000000; border-collapse: collapse;">Registered</th><th style="border: 1px solid #000000; border-collapse: collapse;">Pending for<br/>Tagging & Verification</th><th style="border: 1px solid #000000; border-collapse: collapse;">Verified</th></tr>';
        $output .= '<tr><td style="text-align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['total_filed'] . '</td><td style="text-align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['physical_filed'] . '</td><td style="text-align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['new_efiled'] . '</td><td style="text-align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['refiled'] . '</td><td style="text-align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['registered'] . '</td><td style="text-align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['checked_verified'] . '</td><td style="text-align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['verified'] . '</td>';
        $output .= '</tr></table>';
        $output .= '<br/><br/><table width="100%" style="border: 1px solid #000000; border-collapse: collapse;">
    <tr style="border: 1px solid #000000; border-collapse: collapse;"><th colspan="2" style="border: 1px solid #000000; border-collapse: collapse;">Total Pendency till Date</th></tr> <tr style="border: 1px solid #000000; border-collapse: collapse;"><th style="border: 1px solid #000000; border-collapse: collapse;">Pending for Tagging and Verification</th><th style="border: 1px solid #000000; border-collapse: collapse;">Total Matters Pending for Verification after Re-filing <br> (Registered Matters out of Total Matters)</th></tr>';
        $output .= '<tr><td style="text-align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['tagging_verification'] . '</td><td style="border: 1px solid #000000; border-collapse: collapse; text-align:center;">' . $row['verification_refiled_total'] . ' (' . $row['verification_refiled_reg'] . ' )</td>';
        $output .= '</tr></table>';
        $output .= '<br/><br/><table width="100%" style="border: 1px solid #000000; border-collapse: collapse;">
    <tr><th colspan="6">Work Done Status</th></tr>
    <tr style="border: 1px solid #000000; border-collapse: collapse;"><th colspan="3" style="border: 1px solid #000000; border-collapse: collapse;">Filing</th><th colspan="3" style="border: 1px solid #000000; border-collapse: collapse;">Re-Filing</th></tr>
    <tr style="border: 1px solid #000000; border-collapse: collapse;"><th style="border: 1px solid #000000; border-collapse: collapse;">Alloted</th><th style="border: 1px solid #000000; border-collapse: collapse;">Completed</th><th style="border: 1px solid #000000; border-collapse: collapse;">Remaining</th><th style="border: 1px solid #000000; border-collapse: collapse;">Alloted</th><th style="border: 1px solid #000000; border-collapse: collapse;">Completed</th><th style="border: 1px solid #000000; border-collapse: collapse;">Remaining</th></tr>';
        $output .= '<tr><td style="text-align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['filing_alloted'] . '</td><td style="text-align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['filing_completed'] . '</td><td style="text-align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['filing_pending'] . '</td><td style="text-align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['refiled_alloted'] . '</td><td style="align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['refiled_completed'] . '</td><td style="align:center;border: 1px solid #000000; border-collapse: collapse;">' . $row['refiled_pending'] . '</td>';
        $output .= '</tr></table>';
        echo $output;

}?>