<hr>
<?php
$title="ROP Not Uploaded in Cases Listed between $fromDate and $toDate before $judgeName (as on ".date('d-m-Y h:i:s A').")";
?>
<h4><?=$title;?></h4>
<input type="hidden" name="message" id="message" value="ROP Not Uploaded in Cases Listed between <?=$fromDate?> and <?=$toDate?> before <?=$judgeName?> (as on <?=date('d-m-Y h:i:s A')?>)">
<table id="tblROPNotUploaded" class="table table-striped table-bordered" style="width:100%">
    <thead>
    <tr>
        <th width="5%">S.No.</th>
        <th width="10%">Listing Date</th>
        <th width="5%">Board Type</th>
        <th width="5%">Court Number</th>
        <th width="5%">Item No</th>
        <th width="15">Generated By</th>
        <th width="20%">Case Number</th>
        <th width="35%">Causetitle</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $s_no=1;
    if(!empty($caseList))
    {
        foreach ($caseList as $case)
            {
                $called_by='';         
                $called_by=$ReportModel->getUsercode($case['listing_date'],$case['roster_id'],$case['diary_no'],$case['court_number'],$case['item_number']);

                ?>
                <tr>
                    <td>
                        <?php echo $s_no; ?>
                    </td>
                    <td>
                        <?php echo date("d-m-Y", strtotime($case['listing_date'])); ?>
                    </td>
                    <td><?php $boardType="";
                        switch($case['board_type']){
                            case 'J':
                                $boardType="Court";
                                break;
                            case 'C':
                                $boardType="Chamber";
                                break;
                            case 'R':
                                $boardType="Registrar";
                                break;
                            case 'CC':
                                $boardType="By Circulation";
                                break;
                    }
                    echo $boardType;
                                ?></td>
                    <td>
                        <?php
                        $courtno=$case['court_number'];
                        $courtNoDisplay = 0;
                        if ($courtno == 21)
                            $courtNoDisplay = "R-1";
                        else if ($courtno == 22)
                            $courtNoDisplay = "R-2";
                        else if ($courtno > 30 && $courtno <= 60) {
                            $courtNoDisplay="V-".($courtno-30);
                        }
                        else if ($courtno > 60 && $courtno <= 62) {
                            $courtNoDisplay = "VR-".($courtno-60);
                        }
                        else{
                            $courtNoDisplay=$courtno;
                        }

                        echo $courtNoDisplay; ?>
                    </td>
                    <td>
                        <?php echo $case['item_number']; ?>
                    </td>
                    <td>
                        <?php echo $called_by['user_name'] ?? '';?>
                    </td>
                    <?php
                    $diarynumber=$case['diary_no'];
                    $diarynumber="Diary No. ".substr($diarynumber, 0, -4)."/".substr($diarynumber, -4);
                    ?>

                    <td>
                        <?php echo $diarynumber."<br/>".wordwrap($case['registration_number_desc'],30,"\n",true);?>
                    </td>


                    <td>
                        <?php
                        echo $case['petitioner_name']."<br/><centre>Vs.</centre><br/> ".$case['respondent_name'];
                        ?>
                    </td>
                </tr>
                <?php
                $s_no++;
            }   //for each
        }else{ ?>
            <tr><td colspan="100%">No Record found...</td></tr>
 <?php    }
    ?>
    </tbody>
</table>



 
<link rel="stylesheet" href="<?=base_url()?>/assets/plugins/datatables/jquery.dataTables.min.css">
<link rel="stylesheet" href="<?=base_url()?>/assets/plugins/datatables/buttons.dataTables.min.css">
<script src="<?=base_url()?>/assets/plugins/datatables/jquery.dataTables.js"></script>

<script src="<?=base_url()?>/assets/plugins/datatables/skin/bootstrap/js/dataTables.bootstrap.js"></script>
<script src="<?=base_url()?>/assets/plugins/datatables/extensions/export/dataTables.buttons.min.js"></script>
<script src="<?=base_url()?>/assets/plugins/datatables/extensions/export/buttons.flash.min.js"></script>
<script src="<?=base_url()?>/assets/plugins/datatables/extensions/export/jszip.min.js"></script>
<script src="<?=base_url()?>/assets/plugins/datatables/extensions/export/pdfmake.min.js"></script>
<script src="<?=base_url()?>/assets/plugins/datatables/extensions/export/vfs_fonts.js"></script>
<script src="<?=base_url()?>/assets/plugins/datatables/extensions/export/buttons.html5.min.js"></script>
<script src="<?=base_url()?>/assets/plugins/datatables/extensions/export/buttons.print.min.js"></script>  
<script>
    $.extend( $.fn.dataTable.defaults, {
        "buttons": [
            $.extend( true, {},  {
                extend: 'excelHtml5',
                title: function() {
                    return $('#message').val()
                },
                filename: 'rop_not_uploaded'
            } ),
            $.extend( true, {},  {
                extend: 'pdfHtml5',
                title: function() {
                    return $('#message').val()
                },
                filename: 'rop_not_uploaded'
            } ),
            $.extend( true, {},  {
                extend: 'print',
                title: function() {
                    return $('#message').val()
                },
                filename: 'rop_not_uploaded'
            } )
        ]
    } );
 
$('#tblROPNotUploaded').DataTable({
"paging": true,
"lengthChange": true,
"searching": true,
"ordering": true,
"info": true,
"autoWidth": false,
"scrollY": "60vh",
"scrollX": true,
"scrollCollapse": true,
"footerCallback":"",
dom: 'B<"top"lfip>rt<"bottom"ip><"clear">',
}); 

</script>