<?= view('header'); ?>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <form class="form-horizontal" id="push-form" method="post" action="<?php htmlspecialchars($_SERVER['PHP_SELF']); ?>">
                    <p id="show_error"></p> <!-- This Segment Displays The Validation Rule -->
                    <div class="card">


                        <div class="card-header bg-info text-white font-weight-bolder">SCLSC | Diary Generated BY API
                        </div>

                        <div class="card-body">


                            <div class="form-row">
                                <label for="status">Select Status:</label>
                                <div class="radio">
                                    <label><input checked type="radio" name="status" value="" />All</label>
                                    <label><input type="radio" name="status" value="P" />Pending</label>
                                    <label><input type="radio" name="status" value="D" />Disposed of</label>
                                </div>
                                <input id="btn_search" name="btn_search" type="submit" class="btn btn-success ml-2" value="Click">
                            </div>

                        </div>

                    </div>
                </form>

                <div class="row col-md-12 m-2 p-2" id="result">


                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
</section>
<!-- /.content -->