
<?php if(isset($result) && !empty($result)){ ?>
                <div  class="dataTables_wrapper dt-bootstrap4 query_builder_wrapper_dataTable">

                <table  class="table table-bordered table-striped datatablereport">
                    <thead>
                    <tr>
                        <th>SNo.</th>
                        <th>Diary No.</th>
                        <th>Reg. No.</th>
                        <th>Document Description</th>
                        <th>Remark</th>
                        <th>Status</th>
                        <th>Filed By</th>
                        <th>Advocate</th>
                        <th>Generated By/Date-time</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    $i=1; $cause_title='';
                    foreach ($result as $row) {
                        $ent_dt=!empty($row['ent_dt']) ? date('d-m-Y h:i:s A',strtotime($row['ent_dt'])) : '';
                        ?>
                        <tr>
                            <td><?= $i++;?></td>
                            </th><td><?php echo substr($row['diary_no'],0,-4).'/'.substr($row['diary_no'],-4);?></td>
                            <td><?php echo $row['short_description'].SUBSTR($row['active_fil_no'],3).'/'.$row['active_reg_year'];?></td>
                            <td>
                                <?php
                                echo $row['docnum'].'/'.$row['docyear'].' - ';
                                if($row['doccode']==8) echo "I.A.- ";
                                echo $row['docdesc']; if($row['other1'] != '') echo ' - '.$row['other1'];
                                ?>
                            </td>
                            <td><?php echo $row['remark']; ?></td>
                            <td><?php if($row['doccode']==8){ if($row['iastat']=='P') echo "Pending"; else if($row['iastat']=='D') echo "Disposed";}?></td>
                            <td><?php echo $row['filedby']; ?></td><td><?php echo $row['advname']; ?></td>
                            <td><?php echo $row['entryuser'].'/'.$ent_dt; ?></td>
                        </tr>
                        <?php }?>
                    </tbody>

                </table>
        </div>
    <script>
        $(function () {
            $(".datatablereport").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel",{extend: 'pdfHtml5',orientation: 'landscape',pageSize: 'LEGAL' },
                    { extend: 'colvis',text: 'Show/Hide'}],"bProcessing": true,"extend": 'colvis',"text": 'Show/Hide'
            }).buttons().container().appendTo('.query_builder_wrapper_dataTable .col-md-6:eq(0)');

        });
    </script>
          <?php } ?>
<?php if(isset($result) && empty($result)){ ?>
    <div class="text-center align-items-center"><i class="fas fa-info"> </i> No Record Found</div>
<?php } ?>


